"""Tests for the B6 stage-2 lattice base-phonemization routing.

tugaphone's out-of-lexicon *base* IPA can be generated by the shared
orthography2ipa pronunciation lattice (the beam) instead of the private
grapheme cascade, via :func:`tugaphone.lattice_adapter.lattice_base_ipa` and
the per-dialect ``USE_O2I_LATTICE_BASE`` opt-in.

These tests pin:

- the segment-model boundary handling (canonical layout, glide denasalization);
- that the routing is actually wired into ``WordToken.ipa`` and reads the
  lattice for out-of-lexicon words while the lexicon still wins;
- that every shipped dialect keeps the routing OFF (no regression), and that
  the single opt-in flag is the whole switch;
- a locked OLD-cascade vs NEW-lattice characterization of the known
  divergences, each annotated with which base is the more correct form (the
  adjudication that gates the per-dialect flip; see
  ``docs/lattice-base-migration.md``).
"""
import unicodedata

import pytest

from tugaphone.dialects import (
    AngolanPortuguese, BrazilianPortuguese, EuropeanPortuguese,
    MozambicanPortuguese, TimoresePortuguese,
)
from tugaphone.lattice_adapter import lattice_base_ipa, _denasalize_glide
from tugaphone.registry import list_dialects, get_dialect_inventory
from tugaphone.tokenizer import WordToken


COMBINING_TILDE = "̃"


def _cascade(word, dialect_cls):
    """Base IPA via the private grapheme cascade (lexicon zeroed out)."""
    d = dialect_cls(IRREGULAR_WORDS={"\x00": ""})
    return WordToken(surface=word, word_idx=0, dialect=d).ipa


class _EuropeanLattice(EuropeanPortuguese):
    """European Portuguese with the lattice base routing forced on."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.USE_O2I_LATTICE_BASE = True


# ---------------------------------------------------------------------------
# Segment-model boundary
# ---------------------------------------------------------------------------

class TestSegmentBoundary:
    def test_glide_tilde_stripped_nucleus_kept(self):
        """Nasal off-glide loses its tilde; the nucleus tilde is preserved."""
        assert _denasalize_glide("ɐ̃w̃") == "ɐ̃w"
        assert _denasalize_glide("õj̃") == "õj"
        # nucleus tilde survives, off-glide tilde gone
        assert COMBINING_TILDE in _denasalize_glide("ɐ̃w̃")
        assert not _denasalize_glide("ɐ̃w̃").endswith(COMBINING_TILDE)

    def test_canonical_layout(self):
        """Output is per-syllable, stress-marked, joined by the hiatus token."""
        assert lattice_base_ipa("gato", "pt-PT") == "ˈɡa·tu"
        assert lattice_base_ipa("vinho", "pt-PT") == "ˈvi·ɲu"
        assert lattice_base_ipa("filho", "pt-PT") == "ˈfi·ʎu"

    def test_nasal_diphthong_denasalized_and_restressed(self):
        """``cão``: glide denasalized (``ɐ̃w``) and stress re-placed per syllable.

        The lattice emits ``kɐ̃ˈw̃`` (stress on the off-glide, nasalized glide);
        the adapter yields tugaphone's ``ˈkɐ̃w`` — nucleus-nasal, bare glide,
        stress on the syllable.
        """
        out = lattice_base_ipa("cão", "pt-PT")
        assert out == "ˈkɐ̃w"
        assert "w" + COMBINING_TILDE not in out

    def test_no_grapheme_returns_none(self):
        """A word the lattice cannot tokenize yields None (cascade fallback)."""
        assert lattice_base_ipa("", "pt-PT") is None

    def test_output_is_nfc(self):
        out = lattice_base_ipa("cão", "pt-PT")
        assert out == unicodedata.normalize("NFC", out)


# ---------------------------------------------------------------------------
# Routing wired into WordToken
# ---------------------------------------------------------------------------

class TestRouting:
    def test_oov_word_uses_lattice_when_opted_in(self):
        """An out-of-lexicon word is transcribed from the lattice, not cascade."""
        assert "trasgo" not in EuropeanPortuguese().IRREGULAR_WORDS
        lat = WordToken(surface="trasgo", word_idx=0,
                        dialect=_EuropeanLattice()).ipa
        cas = WordToken(surface="trasgo", word_idx=0,
                        dialect=EuropeanPortuguese()).ipa
        assert lat == lattice_base_ipa("trasgo", "pt-PT")
        # o2i models the EP coda /s/ → [ʃ]; the cascade keeps [s]. The routing
        # genuinely changes the base for this OOV word.
        assert lat == "ˈtɾaʃ·ɡu"
        assert cas == "ˈtɾas·ɡu"
        assert lat != cas

    def test_lexicon_still_wins_with_routing_on(self):
        """The lexicon layer is untouched: an in-lexicon word ignores the lattice."""
        d = _EuropeanLattice()
        assert "gato" in d.IRREGULAR_WORDS
        assert WordToken(surface="gato", word_idx=0, dialect=d).ipa == \
            d.IRREGULAR_WORDS["gato"]

    def test_cascade_used_when_opted_out(self):
        """Default dialect keeps the cascade base for OOV words."""
        assert WordToken(surface="trasgo", word_idx=0,
                         dialect=EuropeanPortuguese()).ipa == \
            _cascade("trasgo", EuropeanPortuguese)


# ---------------------------------------------------------------------------
# No-regression invariant
# ---------------------------------------------------------------------------

class TestOptInInvariant:
    def test_every_shipped_dialect_defaults_off(self):
        """No shipped dialect enables the lattice base (protects the gold)."""
        for code in list_dialects():
            assert get_dialect_inventory(code).USE_O2I_LATTICE_BASE is False

    @pytest.mark.parametrize("factory", [
        EuropeanPortuguese, BrazilianPortuguese, AngolanPortuguese,
        MozambicanPortuguese, TimoresePortuguese,
    ])
    def test_flag_is_the_only_switch(self, factory):
        """Flipping the single flag is what changes the OOV base source."""
        base = factory()
        assert base.USE_O2I_LATTICE_BASE is False
        flipped = factory()
        flipped.USE_O2I_LATTICE_BASE = True
        oov = "trasgo"
        assert oov not in base.IRREGULAR_WORDS
        cascade = WordToken(surface=oov, word_idx=0, dialect=base).ipa
        lattice = WordToken(surface=oov, word_idx=0, dialect=flipped).ipa
        assert lattice == lattice_base_ipa(oov, base.dialect_code)
        # cascade path is unchanged by the presence of the flag machinery
        assert cascade == _cascade(oov, factory)


# ---------------------------------------------------------------------------
# OLD-cascade vs NEW-lattice characterization (flip-gating adjudication)
# ---------------------------------------------------------------------------

class TestCascadeVsLatticeCharacterization:
    """Locks the known base divergences and which side is more correct.

    This is the adjudication table gating the per-dialect flip
    (``docs/lattice-base-migration.md``). ``better`` records, per the task's
    rule, whether the o2i lattice value should be adopted (``"lattice"``) or is
    a reported o2i gap where the cascade is currently more correct
    (``"cascade"``). References: Mateus & d'Andrade (2000), *The Phonology of
    Portuguese*; Cruz-Ferreira (1995), *European Portuguese*, JIPA 25(2).
    """

    # word, dialect, cascade_ipa, lattice_ipa, better, note
    CASES = [
        ("chegou", EuropeanPortuguese, "pt-PT", "ʃɨ·ˈɡow", "ʃɨ·ˈɡo", "cascade",
         "o2i over-monophthongises <ou>; [ow] is correct (M&d'A 2000)"),
        ("campo", EuropeanPortuguese, "pt-PT", "ˈkɐ̃·pu", "ˈkam·pu", "cascade",
         "o2i does not model coda nasalization; [ɐ̃] is correct"),
        ("sim", EuropeanPortuguese, "pt-PT", "ˈsĩ", "ˈsim", "cascade",
         "o2i does not model coda nasalization; [ĩ] is correct"),
        ("trasgo", EuropeanPortuguese, "pt-PT", "ˈtɾas·ɡu", "ˈtɾaʃ·ɡu", "lattice",
         "o2i models EP coda /s/ → [ʃ]; the more correct EP form"),
        ("casa", BrazilianPortuguese, "pt-BR", "ˈka·za", "ˈka·zɐ", "cascade",
         "o2i over-reduces pt-BR final unstressed /a/; [a] is correct"),
        ("rampa", BrazilianPortuguese, "pt-BR", "ˈhɐ̃·pa", "ˈʁam·pɐ", "cascade",
         "o2i: no coda nasalization + wrong final /a/; both cascade features correct"),
        ("casa", AngolanPortuguese, "pt-AO", "ˈka·za", "ˈka·za", "lattice",
         "o2i agrees with the cascade for pt-AO (no reduction)"),
    ]

    @pytest.mark.parametrize(
        "word,dialect_cls,code,cascade_ipa,lattice_ipa,better,note", CASES)
    def test_divergence_locked(self, word, dialect_cls, code,
                               cascade_ipa, lattice_ipa, better, note):
        assert _cascade(word, dialect_cls) == cascade_ipa, note
        assert lattice_base_ipa(word, code) == lattice_ipa, note
        # sanity: the adjudication label is one of the two bases
        assert better in ("cascade", "lattice")
        if better == "lattice":
            # where o2i is adopted-or-equal, it must not be empty
            assert lattice_ipa

    def test_nasalization_gap_is_systematic(self):
        """The blocking o2i gap: pt coda nasalization is entirely absent."""
        for w in ("campo", "santo", "tempo", "mundo", "sim"):
            assert COMBINING_TILDE not in lattice_base_ipa(w, "pt-PT"), (
                f"{w}: o2i unexpectedly produced a nasal vowel — "
                "revisit the flip plan"
            )
