"""Example — who answers for a lect, and why.

Because a dialect is an orthography2ipa lect spec, the pipeline that produced a
transcription is inspectable: ``who_answers`` reports the plugin resolved for
each stage of a lect, and a covered word is answered by the tugalex lexicon
overlay while an out-of-vocabulary word is generated by the lattice.

Run::

    python examples/06_dialect_provenance.py
"""
from orthography2ipa import who_answers

from tugaphone import TugaPhonemizer, resolve_lect


def main() -> None:
    ph = TugaPhonemizer()

    for code in ["pt-PT", "pt-PT-x-porto", "pt-BR"]:
        lect = resolve_lect(code)
        print(f"{code} → lect {lect}")
        print(f"  who_answers: {who_answers(lect)}")

    print("\nlexicon overlay vs lattice-generated:")
    for word in ["gato", "blorfante"]:  # in-lexicon vs invented
        print(f"  {word:12s} → {ph.phonemize_sentence(word, 'pt-PT')}")


if __name__ == "__main__":
    main()
