"""each function in this file is a transformation of ipa: str -> ipa: str

any number of transformations can be applied at runtime, a set of transformations models a regional accent
"""

import re


# Minho Vocalism: Suppression of Standard EP Vowel Centralization
#   Minho speakers are known for favoring "more open vowels".
#   This is interpreted as a resistance to the extreme centralization of unstressed vowels common in the south.

def reduce_vowel_centralization(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Reduced Centralization:
        The highly centralized and reduced vowel /ɨ/, often generated by the baseline G2P from lexical /e/ or /ɛ/ in pre-tonic positions, is resisted.
         /ɨ/→[e] or [ε]/C__C(¬ Stressed, derived from /e/ or /ɛ/)
    """
    # Replace central vowel /ɨ/ with /e/ when between consonants (unstressed environments)
    # Example: /pɨtɨ/ → /petɨ/, /bɨ/ → /be/
    phonemes = re.sub(r'(?<=[pbtdkgfvszʃʒmnɲlr])ɨ(?=[pbtdkgfvszʃʒmnɲlr])', 'e', phonemes)
    return phonemes


def open_vowel_preference(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Open Vowel Preference:
        Minho speakers tend to realize /ɐ/ as a slightly more open [a] in final and unstressed syllables,
        especially before nasal or lateral consonants.
        /ɐ/ → [a] / __[mnɲl]\b
    """
    # phonemes = re.sub(r'ɐ(?=[mnɲl]\b)', 'a', phonemes)
    return phonemes


# Minho Diphthong Realization (Non-Monophthongization)
#   Minho speakers pronounce diphthongs clearly and distinctly, resisting the southern tendency to reduce them.
def retain_ou_diphthong(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Approximation: restore /ow/ sequences that might have been reduced to /o/ in unstressed syllables.

    Retention of 'ou':
        The diphthong represented by <ou> must be retained as a distinct diphthong [ou] or [ow],
        overriding the standard EP tendency to reduce it to [o] in unstressed contexts.
        /o/ → [ow] / (derived from <ou>)

    eg. "ouro" instead of "ôro"
    """
    # NOTE: the lisbon accent reduces ˈow to ˈo
    # this restores "proper portuguese phonetics"
    # rather than adding a transform for minho accent,
    # it's undoing one from lisbon accent that affects the base G2P
    if word.startswith('ou') and phonemes.startswith("ˈo"):
        return "ˈow" + phonemes[2:]
    if "ô" in word:
        return phonemes
    if "ou" in word:
        return re.sub(r'(\w)ˈo(?!w)', r'\1ˈow', phonemes)
    if word == "boa":
        return "bˈowɐ"
    return phonemes


def retain_ei_diphthong(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Retention of 'ei':
        The diphthong <ei> must be retained as [ej], counteracting any tendency towards monophthongization or reduction to [e].
        /e/ → [ej] / __(If derived from grapheme <ei>)

    eg. "leite" instead of "laite"
    """
    # NOTE: the lisbon accent reduces ˈej to ˈɐj
    # this restores "proper portuguese phonetics"
    # rather than adding a transform for minho accent,
    # it's undoing one from lisbon accent that affects the base G2P
    return re.sub(r'(\w)ˈɐj', r'\1ˈej', phonemes)


def conservative_o_nasal_retention(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Conservative Retention of /õ/ :
        Minho retains the older pronunciation of /õ/
        where SEP has generally merged this sound with the nasal diphthong /ɐ̃w/ (written ão).
        Examples include pão and irmão

    """
    if word.endswith("ão") and phonemes.endswith("ˈɐ̃w"):
        return phonemes[:-4] + "ˈõ"
    if word.endswith("ão") and phonemes.endswith("ˈɐ̃ʊ̃"):  # common espeak mistake
        return phonemes[:-5] + "ˈõ"
    return phonemes


#  Minho Consonant Shifts and Affrication (Inventory Divergence)
# The Minho accent introduces explicit changes to the consonant inventory and distribution.
def labial_fricative_stop_merger(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Labial Fricative/Stop Merger:
        The blurring of /b/ and /v/  suggests a phonological merger exploiting the existing EP allophony.
        Standard EP already allows /b/ to become the voiced bilabial approximant [β] intervocalically.
        The Minho rule generalizes this to the lexical phoneme /v/.
        The transformation is a predictable allophone assignment, generalizing the approximant [β] distribution to the lexical phoneme /v/ in weak positions.
    """
    if word.startswith('v') and (phonemes.startswith("vˈ") or phonemes.startswith("vˌ")):
        return "β" + phonemes[1:]
    if word.startswith('ve') and phonemes.startswith("vɨ"):
        return "β" + phonemes[1:]
    return phonemes


def palatal_affrication_ch(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Palatal Affrication of ch:
        Standard EP reduces the historical affricate to the fricative /ʃ/ (e.g., in chaleira 'kettle').
        Minho, however, realizes the digraph <ch> as the voiceless postalveolar affricate /tʃ/ (as in chamber),
        a feature sometimes compared to Spanish pronunciation.

    /ʃ/→[tʃ] (If derived from grapheme <ch>)

    This rule mandates the G2P baseline output retains information about the originating grapheme.
    Given that Portuguese phonology generally lacks dental affricates (/ts dz/)
    the emergence of /tʃ/ is a highly localized, distinguishing dialectal feature.
    """
    if "ch" in word:
        # Replace any /ʃ/ in the phonemes with /tʃ/ if <ch> is in the word
        return phonemes.replace('ʃ', 'tʃ')
    return phonemes


def rhotic_realization(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Rhotic Realization:
    Replace standard EP /ʁ/ with alveolar trill /r/ in syllable onset positions.
    Approximation: replace /ʁ/ with /r/ at the beginning of the word or after a consonant.
    """
    # Replace /ʁ/ at the start of a word
    phonemes = re.sub(r'^ʁ', 'r', phonemes)
    # Replace /ʁ/ after any consonant (syllable onset)
    phonemes = re.sub(r'(?<=[pbtdkgfvszʃʒmnɲlr])ʁ', 'r', phonemes)
    return phonemes


# Other regionalisms
def epenthetic_j_before_palatal(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Epenthetic [j] before palatals:
        In Minho speech, a short glide [j] is often inserted before palatal consonants.
        This phenomenon occurs after a vowel and before /ʎ/, /ɲ/, or /ʃ/ (and sometimes /tʃ/).
        It gives pronunciations like:
            - 'velho'  [ˈvɛʎu] → [ˈvɛjʎu]
            - 'abelha' [aˈbeʎɐ] → [aˈbejʎɐ]
            - 'bolacha' [boˈlaʃɐ] → [boˈlaiʃɐ]
            - 'banha' [ˈbɐɲɐ] → [ˈbajɲɐ]
            - 'ranho' [ˈʁɐɲu] → [ˈʁajɲu]

        Rule:
            V → Vj / __ [ʎ, ɲ, ʃ, tʃ]
    """
    # Insert [j] after a vowel if immediately followed by a palatal consonant.
    #   - (ˈ[aɐeɛ]) captures a preceding tonic vowel ("a" or "e")
    #   - (?=[ʎɲʃ]) is a lookahead that checks if the next char is palatal /ʎ/, /ɲ/, or /ʃ/
    #   - (?!j) avoids double 'j' insertions if already present
    return re.sub(r'(ˈ[aɐeɛ])(?=[ʎɲʃ])(?!j)', r'\1j', phonemes)


def nasal_diphthongization_e(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Nasal Diphthongization of /ẽ/:
        Transform nasal /ẽ/ → [eĩ] when followed by a consonant,
        especially /t, d, n, s, m/

        Examples:
            casamento → kɐzɐˈmẽtu → kɐzɐˈmeĩtu
            doente → duˈẽtɨ → duˈeĩtɨ
            gente → ˈʒẽtɨ → ˈʒeĩtɨ
            quente → ˈkẽtɨ → ˈkeĩtɨ
            acidente → ɐsiˈdẽtɨ → ɐsiˈdeĩtɨ
    """

    # Replace nasal /ẽ/ with diphthong [eĩ] when followed by consonant (not vowel)
    # Negative lookahead (?![aeiouɐɛɔẽɲʎ]) ensures we don’t touch /ẽ/ before vowels
    # Example match: "ˈʒẽtɨ" → "ˈʒeĩtɨ"

    phonemes = re.sub(r'ẽ(?![aeiouɐɛɔẽɲʎ])', 'eĩ', phonemes)
    return phonemes


def nasal_diphthongization_o(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Nasal Diphthongization of /õ/:
        Transform nasal /õ/ → [oũ] when followed by a consonant,
    """
    # Northern speakers often also realize /õ/ → [oũ] in the same way.
    phonemes = re.sub(r'õ(?![aeiouɐɛɔẽɲʎ])', 'oũ', phonemes)
    return phonemes


def rising_diphthong_o(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Rising diphthongization of /o/ → /uo/ in stressed syllables.
    Example:
        Porto  → /puoɾtu/
        Bolo   → /buoɫu/
    """
    # Match tonic /o/ (ˈo) at word-initial or after consonant in stressed syllable
    phonemes = re.sub(r'ˈo', 'ˈuo', phonemes)  # tonic /o/ → /uo/

    return phonemes


def nasal_glide_palatalization(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Nasal Glide Palatalization:
        In Northern Portugal, the final nasal glides [j̃] or [w̃] that follow
        a nasal vowel (e.g., in mãe, põe, bem) are often reinforced or realized
        as a full palatal nasal [ɲ].

        Rule:
            Ṽj̃ → Ṽɲ / _#
            Ṽw̃ → Ṽɲ / _#

        Examples:
            'mãe' [mˈɐ̃j] → [mˈɐ̃jɲ]
            'põe' [põj̃]  → [põɲ]
            'bem' [bẽj̃]  → [bẽɲ]
    """
    nasal_vowels = "ãẽĩõũɐ̃ɛ̃ɔ̃"
    # Match nasal vowel + nasalized glide at word end → nasal vowel + palatal nasal
    phonemes = re.sub(rf'([{nasal_vowels}])[jw]̃$', r'\1ɲ', phonemes)

    # Handle alternative phonemizer outputs that use combining tildes or nasal glides differently
    # e.g. 'ẽj' or 'ẽĩ̯' at the end
    phonemes = re.sub(rf'([{nasal_vowels}])j$', r'\1jɲ', phonemes)
    phonemes = re.sub(rf'([{nasal_vowels}])ĩ̯$', r'\1ɲ', phonemes)

    return phonemes


def nasal_vowel_raising(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Nasal Vowel Raising:
        In Northern Portugal, nasal vowels tend to be slightly raised and/or fronted
        compared to Standard European Portuguese. This is especially evident in /ɐ̃/
        , which may be realized as [ã].

        Rules:
            ɐ̃ → ã

        Examples:
            'mãe'  [mˈɐ̃j] → [mˈãj]
    """
    # /ɐ̃/ → [ã]
    phonemes = phonemes.replace("ɐ̃", "ã")
    return phonemes


## Trasmontano

def intervocalic_s_voicing(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Intervocalic /s/ Voicing:
        In Transmontano and other northern dialects, /s/ is often voiced to [z]
        between vowels or in word-final position after a vowel.
        This mirrors a general lenition pattern found in voiced environments.

        Rules:
            /s/ → [z] / V__V
            /s/ → [z] / V__#

        Examples:
            'moço' [ˈmosu] → [ˈmozu]
            'seis' [ˈsejs] → [ˈzejz]
    """
    vowels = "aeiouɐɛɔɨẽõɐ̃"
    # Intervocalic voicing
    phonemes = re.sub(rf'(?<=[{vowels}])s(?=[{vowels}])', 'z', phonemes)
    # Word-final after vowel
    phonemes = re.sub(rf'(?<=[{vowels}])s(?=$)', 'z', phonemes)
    return phonemes


def initial_z_devoicing(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Word-Initial /z/ Devoicing:
        In Transmontano Portuguese, initial /z/ may be realized as [s] before vowels.
        This can create minimal-pair-like alternations such as:
            'zero' [ˈzeɾu] → [ˈseɾu]
            'zona' [ˈzonɐ] → [ˈsonɐ]

        Rule:
            /z/ → [s] / #__V
    """
    vowels = "aeiouɐɛɔɨẽõɐ̃"
    phonemes = re.sub(rf'(?<=^)(z)(?=[{vowels}])', 's', phonemes)
    return phonemes


def final_nasal_denasalization(word: str, phonemes: str, postag: str = "NOUN") -> str:
    """
    Final Nasal Denasalization:
        In Transmontano Portuguese, final nasal vowels — especially those in -agem words —
        tend to lose nasalization, yielding oral [e] or [ɐ] realizations.

        This reflects a broader tendency toward denasalization in unstressed
        final syllables across northern varieties.

        Rules:
            /ʒẽ$/ → [ʒe]
            /ʒɐ̃$/ → [ʒɐ]
            /ʒõ$/ → [ʒo]

        Examples:
            'viagem' [viˈaʒẽ] → [viˈaʒe]
            'paragem' [pɐˈɾaʒẽ] → [pɐˈɾaʒe]
    """
    phonemes = re.sub(r'ʒẽ$', 'ʒe', phonemes)
    phonemes = re.sub(r'ʒɐ̃$', 'ʒɐ', phonemes)
    phonemes = re.sub(r'ʒõ$', 'ʒo', phonemes)
    return phonemes


if __name__ == "__main__":
    from tugaphone import TugaPhonemizer

    pho = TugaPhonemizer()

    sentences = [
        "O gato dorme.",
        "Tu falas português muito bem.",
        "O comboio chegou à estação.",
        "A menina comeu o pão todo.",
        "Vou pôr a manteiga no frigorífico.",
        "Ele está a trabalhar no escritório.",
        "Choveu muito ontem à noite.",
        "A rapariga comprou um telemóvel novo.",
        "Vamos tomar um pequeno-almoço.",
        "O carro ficou sem gasolina.",
        "boa roupa touro pouco ouro",  # ou
        'beira peixe feito pequeno reino meio',  # ei
        'verdade verde verdadeira boi vaca bacalhau',  # v
        "pão irmão cagão bolhão cão"  # õ
    ]

    for s in sentences:
        for word in s.split():
            word = word.lower()
            phonemes = pho.phonemize_sentence(word, "pt-PT")
            phonemes_m_v1 = reduce_vowel_centralization(word, phonemes)
            phonemes_m_v2 = open_vowel_preference(word, phonemes_m_v1)
            phonemes_m_d1 = retain_ou_diphthong(word, phonemes_m_v2)
            phonemes_m_d2 = retain_ei_diphthong(word, phonemes_m_d1)
            phonemes_m_d3 = conservative_o_nasal_retention(word, phonemes_m_d2)
            phonemes_m_c1 = labial_fricative_stop_merger(word, phonemes_m_d3)
            phonemes_m_c2 = palatal_affrication_ch(word, phonemes_m_c1)
            phonemes_m_c3 = rhotic_realization(word, phonemes_m_c2)

            print(word, "->", phonemes)
            if phonemes_m_c3 != phonemes:
                if phonemes_m_v2 != phonemes:
                    print(phonemes, "-(m_v1)->", phonemes_m_v1, "-(m_v2)->", phonemes_m_v2)
                if phonemes_m_d3 != phonemes_m_v2:
                    print(phonemes_m_v2, "-(m_d1)->", phonemes_m_d1, "-(m_d2)->", phonemes_m_d2, "-(m_d3)->",
                          phonemes_m_d3)
                if phonemes_m_c3 != phonemes_m_d3:
                    print(phonemes_m_d3, "-(m_c1)->", phonemes_m_c1, "-(m_c2)->", phonemes_m_c2, "-(m_c3)->",
                          phonemes_m_c3)

        print("######")
